---
title: "VisAssignment1"
author: "Briana Flynn"
date: "9/11/2020"
output: html_document
---

```{r}
library(ggplot2)
library(tidycensus)
library(tidyverse)
```

```{r}
area_vars_2010 <- load_variables(2010, "sf1")
```

```{r}
vars <- c(tot_hh = "H001001",
         tot_rural_hh = "H002005",
         tot_rent_hh = "H004004",
         avg_hh_size = "H012001",
         tot_pop = "P003001",
         med_age = "P013001",
         old_resident = "P025002",
         live_alone = "P018008",
         white_pop = "P005003",
         black_pop = "P005004",
         asian_pop = "P005006",
         hispanic_pop = "P005010")

MA_tracts <- get_decennial(geography = "tract", variables = vars,
                           state = "MA", county = "Suffolk County",
                           output = "wide") %>%
  mutate(pct_rental = tot_rent_hh / tot_hh,
         pct_old = old_resident / tot_hh,
         pct_alone = live_alone / tot_pop,
         older = pct_old > .25,
         renter = pct_rental >.5,
         majority_race_eth = case_when(
           white_pop / tot_pop > 0.5 ~ "Non-Hispanic White",
           black_pop / tot_pop > 0.5 ~ "Non-Hispanic Black",
           asian_pop / tot_pop > 0.5 ~ "Non-Hispanic Asian",
           hispanic_pop / tot_pop > 0.5 ~ "Hispanic",
           (white_pop + black_pop + asian_pop + hispanic_pop) /
             tot_pop < 0.5 ~ "other",
           TRUE ~ "None")) %>%
  filter(tot_pop > 0, tot_hh > 0) %>%
  select(GEOID, pct_rental, pct_old, renter, older, majority_race_eth, pct_alone, avg_hh_size, tot_pop, tot_hh, tot_rent_hh, med_age)
```
```{r}
ggplot(MA_tracts, 
       aes(x = pct_alone,
           y = med_age,
           color = majority_race_eth,
           size = avg_hh_size)) +
  labs(title="Multivariable Scatterplot")+
  geom_point() +
  scale_x_continuous(name = "Percent of population living alone",
                     breaks = seq(0, 1, by = 0.05), 
                     labels = paste(seq(0, 100, by = 5), "%", sep = "")) +
  scale_y_continuous(name = "Median age within tract",
                     breaks = seq(10, 80, by = 10)) +
  scale_color_discrete(name= "Majority race/ethnicity",
                       labels = c("Hispanic",
                                  "Non-Hispanic Asian",
                                  "Non-Hispanic Black",
                                  "Non-Hispanic White",
                                  "No Majority"))+
  scale_size_continuous(name = "Average Household Size")+
  theme_light() +
  theme(legend.key.size = unit(.75, "cm"))

```

```{r}
ggplot(MA_tracts, 
       aes(x = factor(majority_race_eth), 
           y = pct_alone,
           fill = factor(majority_race_eth))) +
  geom_dotplot(binaxis = "y", dotsize = 0.7) +
  scale_x_discrete(name = "Majority Race/Ethnicity",
                     labels = c("Hispanic",
                                "Non-Hispanic Asian",
                                "Non-Hispanic Black",
                                "Non-Hispanic White",
                                "No Majority")) +
  scale_y_continuous(name = "Percent of Population Living Alone",
                     breaks = seq(0, 1, by = 0.05),
                     labels = paste(seq(0, 100, by = 5), "%", sep = "")) +
  scale_fill_discrete(name = "Majority Race/Ethnicity")+
  theme_light()+
  theme(legend.key.size = unit(.5, "cm"))+
  theme(axis.text.x = element_text(angle = -35))
```



```{r message=FALSE, warning=FALSE}
ggplot(MA_tracts, 
       aes(x = pct_alone,
           y = med_age,
           color = renter,
           fill = renter,
           shape = older)) +
  labs(title="Scatterplot with Trend Analysis")+
  geom_point() +
  stat_smooth(method = "lm") +
  scale_x_continuous(name = "Percent of Population Living Alone",
                     breaks = seq(0, 1, by = 0.1),
                     labels = paste(seq(0, 100, by = 10), "%", sep = "")) +
  scale_y_continuous(name = "Median Age within Tract",
                     breaks = seq(10, 80, by = 10)) +
  scale_color_discrete(name= "Renter or Owner-Dominated Tract",
                       labels = c("Renter-Dominated",
                                  "Owner-Dominated"))+
  scale_fill_discrete(name= "Renter/Owner-Dominated Tract Trend",
      labels = c("Renter-Domintaed",
                 "Owner-Dominated"))+
  scale_shape(name = element_blank(), 
              labels = c("<25% of Population is 65+", ">25% of Population is 65+")) +
  theme_light() 
```

```{r}
ggplot(MA_tracts, aes(x = renter, y = majority_race_eth, fill = pct_alone)) +
 labs(title="Heat Tiles")+
  geom_tile() +
  scale_y_discrete(name = "Majority Race/Ethnicity")+
  scale_x_discrete(name = "Renter or Owner-Dominated Tract",
                   labels = c("Renter-Dominated",
                              "Owner-Dominated"))+
  labs(fill = "Percent of Residents Living Alone")+
  theme_minimal() 
```

```{r}
ggplot(MA_tracts, aes(x = majority_race_eth, fill = older)) +
  geom_bar() +
  labs(title="Stacked Bar Chart")+
  scale_y_continuous(name = "Number of tracts") +
  scale_x_discrete(name = "Majority race/ethnicity",
                       labels = c("Hispanic",
                                  "Non-Hispanic\nAsian",
                                  "Non-Hispanic Black",
                                  "Non-Hispanic\nwhite",
                                  "No majority")) +
  scale_fill_discrete(name = "Presence of Large Older Population",
                        labels = c("<25% of Population is 65+",
                                   ">25% of Population is 65+")) +
  theme_light()+
  theme(axis.text.x = element_text(angle = 270))
```

```{r message=FALSE, warning=FALSE}
ggplot(MA_tracts, 
       aes(x = majority_race_eth,
           y = med_age,
           fill = majority_race_eth)) +
  labs(title="Violin Plot")+
  geom_violin(width=2, size=0.2, alpha = 0.75) +
  scale_x_discrete(name = "Majority Race/Ethnicity",
                       labels = c("Hispanic",
                                  "Non-Hispanic Asian",
                                  "Non-Hispanic Black",
                                  "Non-Hispanic white",
                                  "No Majority")) +
  scale_y_continuous(name = "Median Age Within Tract",
                     breaks = seq(10, 80, by = 10)) +
  theme_minimal() +
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = -45))
```

```{r}
 ggplot(MA_tracts, aes(x=majority_race_eth, y=pct_old, fill = renter)) +
    labs(title="Box Plot")+
    geom_boxplot() +
    scale_fill_discrete(name = "Renter-or-Owner Dominated Tract") +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    scale_y_continuous(name = "Percent of residents 65+",
                     breaks = seq(0, 1, by = 0.1),
                     labels = paste(seq(0, 100, by = 10), "%", sep = "")) +
    scale_x_discrete(name = "Majority Race/Ethnicity")+
    theme_light()+
 theme(axis.text.x = element_text(angle = -45))
```



```{r message=FALSE, warning=FALSE}
ggplot(MA_tracts, 
       aes(x = med_age,
           y = tot_pop)) +
  labs(title="Nonsensical Polar Coordinate Chart")+
  geom_point(alpha = 0.5, size = 0.5) +
  stat_smooth(color = "blue", linetype = 2, size = 1.0) +
  scale_x_continuous(name = "Median Age",
                     trans = "log",
                     breaks = seq(1, 100, by = 10)) +
  scale_y_continuous(name = "Tract population",
                     trans = "log",
                     breaks = c(10, 100, 1000, 10000),
                     labels = c("10", "100", "1,000", "10,000")) +
  coord_polar(theta = "x") +
  theme_bw() 
```

```{r}
ggplot(MA_tracts, aes(x=pct_rental)) +
  labs(title="Area Chart")+
  geom_density(fill="lightpink", color="lightpink", alpha=0.8) +
  scale_x_continuous(name = "Percent of Rental Households in Tract",
                     breaks = seq(0, 1, by = 0.1),
                     labels = paste(seq(0, 100, by = 10), "%", sep = "")) +
  scale_y_continuous("Density")+
  theme_minimal()
```

```{r}
ggplot(MA_tracts, aes(x=older, fill = majority_race_eth)) +
  labs(title="Stacked Bar Chart")+
  geom_bar() + 
  scale_y_continuous(name = "Number of Tracts") +
  scale_x_discrete(name = "More than 25% of Population is over 65") +
  scale_fill_discrete(name = "Majority Race/Ethnicity")+
  theme_bw()
```


